"""empty message

Revision ID: 330ca9fe3422
Revises: 02f8ba1abb59
Create Date: 2020-07-19 12:09:26.617955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '330ca9fe3422'
down_revision = '02f8ba1abb59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artists', 'genres')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('genres', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
